In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
import json
# Import API key
#from api_keys import gkey
file_to_load = 'outputs/2018_fires'
pd.set_option('mode.chained_assignment', None)
# Read Purchasing File and store into Pandas data frame
fire_df = pd.read_csv(file_to_load)

,Unnamed: 0,Name,Acres Burned,Latitude,Longitude,Fire Started,Fire Extinguished
0,0,Aqueduct Fire,30.0,35.92436,-119.94083,2018-04-12,2019-01-03
1,1,Montecito Flooding / Mudflows,0.0,0.00000,0.00000,2018-01-09,2019-01-03
2,2,Haycamp Fire,50.0,35.96689,-121.28185,2018-02-07,2019-01-03
3,3,Pleasant Fire,2070.0,37.40208,-118.50235,2018-02-18,2019-01-03

In [27]:
nocoords = fire_df[fire_df['Latitude'] == 0.00000 ].index
fire_df.drop(nocoords, inplace= True)
firehead= fire_df.tail(40)
firehead

,Unnamed: 0,Name,Acres Burned,Latitude,Longitude,Fire Started,Fire Extinguished
269,269,Soboba Fire,25.0,33.804060,-116.931880,2018-09-14,2019-01-04
270,270,Meyers Fire,12.0,38.744800,-120.656720,2018-09-20,2019-01-04
271,271,Charlie Fire,3380.0,34.482290,-118.608580,2018-09-22,2019-01-04
272,272,Oak Fire,360.0,37.387890,-119.689120,2018-09-22,2019-01-04
273,273,Copper Fire,53.0,40.336420,-120.930050,2018-09-22,2019-01-04
274,274,Wilson Fire,261.0,40.342560,-121.430250,2018-09-28,2019-01-04
275,275,Silver Fire,76.0,40.593900,-122.171730,2018-09-28,2019-01-04
276,276,Quimby Fire,30.0,37.335630,-121.758150,2018-09-23,2019-01-04
277,277,Nimshew Fire,33.0,39.841510,-121.621680,2018-09-24,2019-01-04
278,278,Shandon Fire,80.0,-120.258000,-120.258000,2018-09-29,2019-01-04
279,279,Keenbrook Fire,53.0,34.241380,-117.424310,2018-09-26,2019-01-04
280,280,Nacimiento Fire,150.0,35.976770,-121.248980,2018-10-02,2019-01-04
281,281,Eagle Fire,32.0,36.938674,-119.312777,2018-10-02,2019-01-04
282,282,Sun Fire,3889.0,40.220278,-122.180000,2018-10-07,2019-01-04
283,283,Park Fire,63.0,37.176944,-121.686944,2018-10-07,2019-01-04
284,284,Iron Gate Fire,15.0,41.940460,-122.439330,2018-10-10,2019-01-04
286,286,Winters Fire,160.0,38.456730,-121.946580,2018-10-12,2019-01-04
287,287,Priest Fire,167.0,36.184010,-120.699550,2018-10-13,2019-01-04
288,288,Tower Fire,12.0,40.496180,-122.515970,2018-10-14,2019-01-04
289,289,Masonic Fire,38.0,40.608660,-122.383660,2018-10-14,2019-01-04
290,290,Powellton Fire,10.0,39.934270,-121.541030,2018-10-15,2019-01-04
291,291,Camino Fire,58.0,35.176930,-120.488610,2018-10-19,2019-01-04
292,292,Market Fire,120.0,36.477660,-119.104330,2018-10-24,2019-01-04
293,293,June Fire,550.0,39.365290,-121.517070,2018-10-30,2019-01-04
294,294,Rincon Fire,17.0,37.012500,-122.046000,2018-11-03,2019-01-04
295,295,Brushy Fire,35.0,39.621940,-123.287740,2018-11-08,2019-01-04
296,296,Camp Fire,153336.0,39.813400,-121.434700,2018-11-08,2018-11-25
297,297,Adams Fire,60.0,40.346652,-122.308479,2018-11-05,2019-01-04
298,298,Horn Fire,88.0,40.831160,-120.193360,2018-11-08,2019-01-04
299,299,Nurse Fire,1500.0,38.213960,-121.942400,2018-11-08,2019-01-04
300,300,Hill Fire,4531.0,34.226850,-118.934440,2018-11-08,2019-01-04
301,301,Woolsey Fire,96949.0,34.235000,-118.701280,2018-11-08,2019-01-04
302,302,Honey Flooding,0.0,39.712170,-121.773850,2018-11-29,2019-01-04
303,303,Morgan Fire,20.0,37.811110,-121.794400,2018-11-15,2019-01-04
304,304,Green Hill Fire,10.0,40.888785,-124.001849,2018-11-12,2019-01-04
305,305,Sierra Fire,147.0,34.180750,-117.431840,2018-11-13,2019-01-04
306,306,Niles Fire,20.0,37.611580,-121.941820,2018-11-14,2019-01-04
307,307,Briggs Fire,150.0,34.301667,-119.099167,2018-11-15,2019-01-04
308,308,Peak Fire,186.0,34.267348,-118.643816,2018-11-12,2019-01-04
309,309,Bear Fire,10.0,37.128570,-122.120360,2018-11-16,2019-01-04

In [14]:
datelist=[]
temp = []
windspeed= []
precip = []
humidity = []
visi = []
pressure = []
cloudcover = []
windgust = []
uvindex = []
location = ''
date = ''

In [21]:
base_url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx"
api_key='e13793a6f1bf4f86a8f20558202204'
#location = '35.924360,-119.940830'

call = f'http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key={api_key}&q={location}&format=json&date={date}&endate={date}&tp=24'


for index, row in fire_df.iterrows():
    lat = row["Latitude"]
    lng = row["Longitude"]
    location = f"{lat},{lng}"
    date = row['Fire Started']
    call = f'http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key={api_key}&q={location}&format=json&date={date}&endate={date}&tp=24'
    response = requests.get(call).json()
    try: 
        datelist.append((response['data']['weather'][0]['date']))
        temp.append(response['data']['weather'][0]['maxtempF'])
        windspeed.append(response['data']['weather'][0]['hourly'][0]['windspeedMiles'])
        precip.append(response['data']['weather'][0]['hourly'][0]['precipMM'])
        humidity.append(response['data']['weather'][0]['hourly'][0]['humidity'])
        visi.append(response['data']['weather'][0]['hourly'][0]['visibilityMiles'])
        pressure.append(response['data']['weather'][0]['hourly'][0]['pressureInches'])
        cloudcover.append(response['data']['weather'][0]['hourly'][0]['cloudcover'])
        windgust.append(response['data']['weather'][0]['hourly'][0]['WindGustMiles'])
        uvindex.append(response['data']['weather'][0]['hourly'][0]['uvIndex'])
 #   hotel_df.loc[index, "Hotel Name"] = response["results"][0]["name"]
    except:
        print(f"couldn't find information for {index}" )
#print(response)    
  #  hist_weather_data_2010 = retrieve_hist_data(api_key,
                               # location,
                               # date,
                               # end_date,
                               # frequency,
                               # location_label = False,
                               # export_csv = True,
                               # store_df = True)

couldn't find information for 227
couldn't find information for 278
{'data': {'request': [{'type': 'LatLon', 'query': 'Lat 37.13 and Lon -122.12'}], 'weather': [{'date': '2018-11-16', 'astronomy': [{'sunrise': '07:49 AM', 'sunset': '05:58 PM', 'moonrise': '02:46 PM', 'moonset': '01:03 AM', 'moon_phase': 'First Quarter', 'moon_illumination': '56'}], 'maxtempC': '20', 'maxtempF': '68', 'mintempC': '12', 'mintempF': '53', 'avgtempC': '14', 'avgtempF': '58', 'totalSnow_cm': '0.0', 'sunHour': '8.7', 'uvIndex': '4', 'hourly': [{'time': '24', 'tempC': '20', 'tempF': '68', 'windspeedMiles': '2', 'windspeedKmph': '3', 'winddirDegree': '120', 'winddir16Point': 'ESE', 'weatherCode': '113', 'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png'}], 'weatherDesc': [{'value': 'Sunny'}], 'precipMM': '0.0', 'precipInches': '0.0', 'humidity': '31', 'visibility': '10', 'visibilityMiles': '6', 'pressure': '1016', 'pressureInches': '30', 'cloudcover': '4', 'HeatIndexC': '17', 'HeatIndexF': '63', 'DewPointC': '-0', 'DewPointF': '32', 'WindChillC': '17', 'WindChillF': '63', 'WindGustMiles': '3', 'WindGustKmph': '5', 'FeelsLikeC': '17', 'FeelsLikeF': '63', 'uvIndex': '4'}]}]}}

In [29]:
data_df = pd.DataFrame({'Precipitation(MM)':precip, 
           'Humidity':humidity,
           'Temperature':temp, 
           'Humidity': humidity,
           'Wind Speed': windspeed,
            'Wind Gust': windgust,
            'Temperature':temp,
           'Cloud Cover':cloudcover,
            'Date':datelist})
data_df

,Precipitation(MM),Humidity,Temperature,Wind Speed,Wind Gust,Cloud Cover,Date
0,0.1,48,64,15,21,6,2018-04-12
1,0.0,58,68,5,9,0,2018-02-07
2,0.1,35,47,11,16,1,2018-02-18
3,0.0,67,74,5,7,8,2018-05-14
4,0.1,48,64,15,21,6,2018-04-12
...,...,...,...,...,...,...,...
305,0.0,11,70,8,11,16,2018-11-13
306,0.0,22,71,3,4,6,2018-11-14
307,0.0,38,70,5,8,48,2018-11-15
308,0.0,19,68,9,15,0,2018-11-12
309,0.0,31,68,2,3,4,2018-11-16

In [33]:
data_df.to_csv("outputs/fireweather2018.csv" , index = True)

In [ ]:
print(response['data']['weather'])